version: '2'
services:
  etudiant-app:
    image: etudiant
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://etudiant-mysql:3306/etudiant?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://etudiant-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://etudiant-elasticsearch:9200
    ports:
      - 9000:9000
  etudiant-mysql:
    extends:
      file: mysql.yml
      service: etudiant-mysql
  etudiant-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: etudiant-elasticsearch
